# 纯运行环境，不包含构建过程
ARG RUNTIME_IMAGE=lazy-aiops:latest

FROM ${RUNTIME_IMAGE}
WORKDIR /app

ENV TZ=Asia/Shanghai

# 直接复制本地构建好的 Linux 二进制文件
COPY app_server_host ./lazy-auto-ops
COPY configs ./configs

# 直接复制本地构建好的前端 dist
COPY web/static ./web/static

RUN mkdir -p data
EXPOSE 8080

CMD ["./lazy-auto-ops"]
